name: chat_package
description:  Fully functional chat ui for flutter, with functionality to send text, voice notes,and images
version: 1.0.0
homepage: https://github.com/MOUKZ/chat_package

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  just_audio: ^0.9.30
  record: ^4.4.3
  intl: ^0.17.0
  photo_view: ^0.14.0
  stop_watch_timer: ^2.0.0
  provider: ^6.0.4
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3  
  freezed: ^2.3.2

  

flutter:

